name       : python-padatious
version    : 0.4.7
release    : 4
source     :
    - https://files.pythonhosted.org/packages/33/c1/a54ac3f8fe5fac7fc9537beb90576673a660f3da9147e1317adf6e4c3cfb/padatious-0.4.7.tar.gz : 3c235942ff4151a3c36536fd776bd8a6d4d57c97046723d2fa80a89b34faac1f
license    : Apache-2.0
component  : programming.python
summary    : A neural network intent parser
description: |
    An efficient and agile neural network intent parser
rundeps    :
    - python-fann2
    - python-padaos
    - python-xxhash
build      : |
    %python3_setup
install    : |
    %python3_install
